#!/usr/bin/env bash
. script/env
ARGS="${@:-tests/}"
set -e
PYTHONPATH="." pytest $ARGS
flake8 --max-line-length 50000 --ignore W503,F812 tensorflow_serving_client tests
# PYTHONPATH="." pytest --cov tensorflow_serving_client tests