#!/usr/bin/env bash
. script/env
ARGS="${@:-tests/}"
set -e

# Wait until the tensorflow-serving connection is up.
for port in $(seq 9001 9006); do
  n=0
  until [ $n -ge 30 ]
  do
    if [[ $(nc localhost $port -w 1 | wc -c) -ne 0 ]]; then break; fi
    n=$[$n+1]
    echo "Waiting for tensorflow-serving on $port..."
    sleep 5
  done
done

# Run tests and linting checks.
PYTHONPATH="." pytest --cov=./ -v -s $ARGS
flake8 --max-line-length 50000 --ignore W503,F812 tensorflow_serving_client tests --exclude tensorflow_serving_client/protos

# Upload coverage for CI.
if [ -n "$CI" ]; then
  pip install codecov
  codecov
fi
